title: FileSender server software
description: FileSender is a web based application that allows authenticated users to securely and easily send arbitrarily large files to other users.
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
